import os
API_ID = int(os.environ.get("API_ID", None))
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
#OPENAI_KEY = os.environ.get("OPENAI_KEY",None)
BOT_USERNAME = os.environ.get("BOT_USERNAME","Lucy_Filter_bot")
SUDO=os.environ.get("SUDO","6497757690")
BOT_NAME = os.environ.get("BOT_NAME","𝐋ᴜᴄʏ")
START_IMG = os.environ.get("START_IMG","https://graph.org/file/05cf2e807ab29ca0ca487.jpg")
STKR = os.environ.get("STKR","CAACAgEAAx0CRjAUHgABAsULZASkFZUsTQTw2k-FvC2SBJnd-vAAAokCAALW9iBFzemsQBDIqWkuBA")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL","team_netflix")
OWNER_USERNAME = os.environ.get("OWNER_USERNAME",None)
SUDO=os.environ.get("SUDO","5910057231")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","weebs_support")
BARD_TOKEN=os.environ.get("BARD_TOKEN","AIzaSyAjlZfV8QfFmXRIyAdBfrqf2TdHHJgJ3o0")
